/* @bruin
name: stripe_stage.invoices
type: bq.sql
description: >
  Conformed invoice facts for billings, current AR, and invoice-line analysis.
  Amounts are native-currency minor units and are not accounting revenue.
  invoice_lines_has_more flags Stripe's paginated embedded line payload; a true
  value means the flattened invoice-line model is not a complete subledger.

materialization:
  type: table

depends:
  - stripe_raw.invoice

owner: dana@harborside.example
tags:
  - harborside
  - stripe_stage
  - stripe
  - billing
  - stage
  - invoices

domains:
  - finance
meta:
  layer: stage
  tier: silver
  team: finance
  cost_center: "FIN-204"

columns:
  - name: stripe_invoice_id
    type: STRING
    description: Stripe invoice identifier and natural key.
    primary_key: true
    checks:
      - name: not_null
      - name: unique
  - name: stripe_customer_id
    type: STRING
    description: Stripe billing customer the invoice is billed to.
  - name: invoice_created_at
    type: TIMESTAMP
    description: When the invoice was created in Stripe.
  - name: invoice_due_at
    type: TIMESTAMP
    description: >
      When payment is due. Stripe only sets a due date for invoices collected
      with `send_invoice`, so it is null for automatically charged invoices.
  - name: invoice_finalized_at
    type: TIMESTAMP
    description: >
      When the invoice was finalized, read from Stripe's status transitions. The
      billings report falls back to `invoice_created_at` when it is missing.
  - name: invoice_status
    type: STRING
    description: >
      Stripe invoice status. The billings report excludes `draft` and `void`
      invoices.
  - name: billing_reason
    type: STRING
    description: Why Stripe created the invoice, for example `subscription_cycle`.
  - name: collection_method
    type: STRING
    description: >
      How the invoice is collected, either `charge_automatically` or
      `send_invoice`.
  - name: currency
    type: STRING
    description: Three-letter ISO currency code the invoice is billed in.
  - name: is_live_mode
    type: BOOL
    description: Whether the invoice exists in Stripe live mode.
  - name: is_paid
    type: BOOL
    description: >
      Whether the invoice is currently paid. This is present state, not a
      historical collections measure.
  - name: payment_attempt_count
    type: INT64
    description: Number of payment attempts Stripe has made for the invoice.
  - name: invoice_amount_due_minor
    type: NUMERIC
    description: Amount due in native-currency minor units.
  - name: invoice_amount_paid_minor
    type: NUMERIC
    description: Amount paid in native-currency minor units.
  - name: invoice_amount_remaining_minor
    type: NUMERIC
    description: Amount still owed in native-currency minor units.
  - name: invoice_subtotal_minor
    type: NUMERIC
    description: Subtotal before discounts and taxes, in minor units.
  - name: invoice_total_minor
    type: NUMERIC
    description: >
      Invoice total after discounts and taxes, in minor units. It is the
      billings measure used by `stripe_report.monthly_invoice_billings`.
  - name: is_subscription_invoice
    type: BOOL
    description: >
      Whether the invoice was generated by a subscription, derived from
      `billing_reason`.
  - name: invoice_lines_has_more
    type: BOOL
    description: >
      Whether Stripe reports more pages in the embedded invoice.lines payload.
      True means invoice_line_items is incomplete; null means the source did
      not provide a parseable pagination indicator.
  - name: invoice_lines
    type: JSON
    description: >
      Embedded Stripe invoice-line payload, flattened by
      `stripe_stage.invoice_line_items`.

unit_tests:
  - name: flags_subscription_invoices_and_casts_amounts
    description: >
      A `subscription_cycle` invoice is flagged as a subscription invoice while
      a `manual` invoice is not, and the raw integer minor-unit amounts and
      payment attempt count are cast to their conformed types.
    inputs:
      - asset: stripe_raw.invoice
        rows:
          - id: in_1SubCycle0001
            object: invoice
            created: 1704067200
            customer: cus_acme
            status: paid
            status_transitions: '{"finalized_at": 1704070800}'
            billing_reason: subscription_cycle
            collection_method: charge_automatically
            currency: usd
            amount_due: 9900
            amount_paid: 9900
            amount_remaining: 0
            subtotal: 9900
            total: 9900
            attempt_count: 1
            paid: true
            livemode: true
            lines: '{"has_more": false, "data": []}'
          - id: in_2Manual0002
            object: invoice
            created: 1706745600
            customer: cus_pine
            status: open
            status_transitions: '{"finalized_at": 1706749200}'
            billing_reason: manual
            collection_method: send_invoice
            currency: usd
            amount_due: 5000
            amount_paid: 0
            amount_remaining: 5000
            subtotal: 5000
            total: 5000
            attempt_count: 0
            paid: false
            livemode: true
            lines: '{"has_more": false, "data": []}'
    expected:
      match: exact
      rows:
        - stripe_invoice_id: in_1SubCycle0001
          stripe_customer_id: cus_acme
          invoice_status: paid
          billing_reason: subscription_cycle
          currency: usd
          is_paid: true
          payment_attempt_count: 1
          invoice_amount_due_minor: 9900
          invoice_amount_paid_minor: 9900
          invoice_amount_remaining_minor: 0
          invoice_subtotal_minor: 9900
          invoice_total_minor: 9900
          is_subscription_invoice: true
          invoice_lines_has_more: false
        - stripe_invoice_id: in_2Manual0002
          stripe_customer_id: cus_pine
          invoice_status: open
          billing_reason: manual
          currency: usd
          is_paid: false
          payment_attempt_count: 0
          invoice_amount_due_minor: 5000
          invoice_amount_paid_minor: 0
          invoice_amount_remaining_minor: 5000
          invoice_subtotal_minor: 5000
          invoice_total_minor: 5000
          is_subscription_invoice: false
          invoice_lines_has_more: false
@bruin */

SELECT
  id AS stripe_invoice_id,
  customer AS stripe_customer_id,
  TIMESTAMP_SECONDS(SAFE_CAST(created AS INT64)) AS invoice_created_at,
  TIMESTAMP_SECONDS(SAFE_CAST(due_date AS INT64)) AS invoice_due_at,
  TIMESTAMP_SECONDS(
    LAX_INT64(status_transitions.finalized_at)
  ) AS invoice_finalized_at,
  status AS invoice_status,
  billing_reason,
  collection_method,
  currency,
  livemode AS is_live_mode,
  paid AS is_paid,
  SAFE_CAST(attempt_count AS INT64) AS payment_attempt_count,
  SAFE_CAST(amount_due AS NUMERIC) AS invoice_amount_due_minor,
  SAFE_CAST(amount_paid AS NUMERIC) AS invoice_amount_paid_minor,
  SAFE_CAST(amount_remaining AS NUMERIC) AS invoice_amount_remaining_minor,
  SAFE_CAST(subtotal AS NUMERIC) AS invoice_subtotal_minor,
  SAFE_CAST(total AS NUMERIC) AS invoice_total_minor,
  billing_reason IN (
    'subscription_create',
    'subscription_cycle',
    'subscription_update',
    'subscription_threshold'
  ) AS is_subscription_invoice,
  LAX_BOOL(lines.has_more) AS invoice_lines_has_more,
  lines AS invoice_lines
FROM stripe_raw.invoice;
